[[custom_groups]]
name = "Steam"
type = "select"
rule = [
    "[]China",
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT"
]

[[custom_groups]]
name = "Xbox"
type = "select"
rule = [
    "[]China",
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT"
]

[[custom_groups]]
name = "OneDrive"
type = "select"
rule = [
    "[]Proxies",
    "[]China",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT"
]

[[custom_groups]]
name = "Microsoft"
type = "select"
rule = [
    "[]China",
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT"
]

[[custom_groups]]
name = "GameDirect"
type = "select"
rule = [
    "[]China",
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT"
]

[[custom_groups]]
name = "MagicArena"
type = "select"
rule = [
    "[]US",
    "[]China",
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]DIRECT"
]

[[custom_groups]]
name = "CustomDirect"
type = "select"
rule = [
    "[]DIRECT",
    "[]China",
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US"
]

[[custom_groups]]
name = "CustomProxy"
type = "select"
rule = [
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]China",
    "[]DIRECT"
]

[[custom_groups]]
name = "PayPal"
type = "select"
rule = [
    "[]China",
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT"
]

[[custom_groups]]
name = "Apple"
type = "select"
rule = [
    "[]China",
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT"
]

[[custom_groups]]
name = "StreamingSE"
type = "select"
rule = [
    "[]China",
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT"
]

[[custom_groups]]
name = "Streaming"
type = "select"
rule = [
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT"
]

[[custom_groups]]
name = "MangaCN"
type = "select"
rule = [
    "[]DIRECT",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]Proxies"
]

[[custom_groups]]
name = "MangaProxy"
type = "select"
rule = [
    "[]HK",
    "[]SG",
    "[]TW",
    "[]JP",
    "[]US",
    "[]Proxies",
    "[]DIRECT"
]

[[custom_groups]]
name = "BaozimhCN"
type = "select"
rule = [
    "[]DIRECT",
    "[]TW,
    "[]SG",
    "[]JP",
    "[]HK",
    "[]US",
    "[]Proxies"
]

[[custom_groups]]
name = "Baozimh"
type = "select"
rule = [
    "[]TW",
    "[]SG",
    "[]JP",
    "[]HK",
    "[]US",
    "[]Proxies",
    "[]DIRECT"
]

[[custom_groups]]
name = "Manhuagui"
type = "select"
rule = [
    "[]TW",
    "[]SG",
    "[]JP",
    "[]HK",
    "[]US",
    "[]Proxies",
    "[]DIRECT"
]

[[custom_groups]]
name = "Telegram"
type = "select"
rule = [
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT"
]

[[custom_groups]]
name = "GMail"
type = "select"
rule = [
    "[]Proxies",
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    ".*",
    "[]DIRECT"
]

[[custom_groups]]
name = "OutLan"
type = "select"
rule = [
    "[]MyHost",
    "[]DIRECT"
]

[[custom_groups]]
name = "Proxies"
type = "select"
rule = [
    "[]HK",
    "[]SG",
    "[]JP",
    "[]TW",
    "[]US",
    "[]DIRECT",
    ".*"
]

[[custom_groups]]
name = "China"
type = "select"
rule = [
    "[]DIRECT",
    "(China|回国|中国|江苏|北京|上海|广州|深圳|杭州|常州|徐州|青岛|宁波|镇江|back)",
    "[]MyHost",
    "[]Proxies"
]

[[custom_groups]]
name = "Final"
type = "select"
rule = [
    "[]Proxies",
    "[]China",
    "[]DIRECT"
]

[[custom_groups]]
name = "HK"
type = "select"
rule = [
    "(港|HK)"
]

[[custom_groups]]
name = "SG"
type = "select"
rule = [
    "(新加坡|狮城|新|SG)"
]

[[custom_groups]]
name = "TW"
type = "select"
rule = [
    "(台|新北|彰化|TW)"
]

[[custom_groups]]
name = "JP"
type = "select"
rule = [
    "(日本|东京|大阪|埼玉|JP)"
]

[[custom_groups]]
name = "US"
type = "select"
rule = [
    "(美|洛杉矶|硅谷|达拉斯|费利蒙|凤凰城|芝加哥|圣何塞|西雅图|圣克拉拉|US)"
]
