[[rulesets]]
group = "OutLan"
ruleset = "rules/AdditionalRuleList/rulesets/OutLan.list"

[[rulesets]]
group = "CustomDirect"
ruleset = "rules/AdditionalRuleList/rulesets/CustomDirect.list"

[[rulesets]]
group = "CustomProxy"
ruleset = "rules/AdditionalRuleList/rulesets/CustomProxy.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/AdditionalRuleList/rulesets/ProcessDirect.list"

[[rulesets]]
group = "Proxies"
ruleset = "rules/AdditionalRuleList/rulesets/Proxy.list"

[[rulesets]]
group = "China"
ruleset = "rules/AdditionalRuleList/rulesets/Direct.list"

[[rulesets]]
group = "GMail"
ruleset = "rules/AdditionalRuleList/rulesets/GMail.list"

[[rulesets]]
group = "SteamProxy"
ruleset = "rules/AdditionalRuleList/rulesets/SteamProxy.list"

[[rulesets]]
group = "Steam"
ruleset = "rules/AdditionalRuleList/rulesets/Steam.list"

[[rulesets]]
group = "Xbox"
ruleset = "rules/AdditionalRuleList/rulesets/Xbox.list"

[[rulesets]]
group = "OneDrive"
ruleset = "rules/AdditionalRuleList/rulesets/OneDrive.list"

[[rulesets]]
group = "Microsoft"
ruleset = "rules/AdditionalRuleList/rulesets/Microsoft.list"

[[rulesets]]
group = "AI"
ruleset = "rules/AdditionalRuleList/rulesets/AI.list"

[[rulesets]]
group = "GameDirect"
ruleset = "rules/AdditionalRuleList/rulesets/GameDirect.list"

[[rulesets]]
group = "MagicArena"
ruleset = "rules/AdditionalRuleList/rulesets/MagicArena.list"

[[rulesets]]
group = "PayPal"
ruleset = "rules/AdditionalRuleList/rulesets/PayPal.list"

[[rulesets]]
group = "Apple"
ruleset = "rules/AdditionalRuleList/rulesets/Apple.list"

[[rulesets]]
group = "StreamingSE"
ruleset = "rules/AdditionalRuleList/rulesets/StreamingSE.list"

[[rulesets]]
group = "Streaming"
ruleset = "rules/AdditionalRuleList/rulesets/treaming.list"

[[rulesets]]
group = "MangaCN"
ruleset = "rules/AdditionalRuleList/rulesets/Manga/MangaCN.list"

[[rulesets]]
group = "MangaProxy"
ruleset = "rules/AdditionalRuleList/rulesets/Manga/MangaProxy.list"

[[rulesets]]
group = "BaozimhCN"
ruleset = "rules/AdditionalRuleList/rulesets/Manga/BaozimhCN.list"

[[rulesets]]
group = "Baozimh"
ruleset = "rules/AdditionalRuleList/rulesets/Manga/Baozimh.list"

[[rulesets]]
group = "Manhuagui"
ruleset = "rules/AdditionalRuleList/rulesets/Manga/Manhuagui.list"

[[rulesets]]
group = "Telegram"
ruleset = "rules/AdditionalRuleList/rulesets/Telegram.list"

[[rulesets]]
group = "Proxies"
ruleset = "rules/SukkaW/Source/non_ip/global.conf"

[[rulesets]]
group = "China"
ruleset = "rules/AdditionalRuleList/rulesets/China.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/LocalAreaNetwork.list"

[[rulesets]]
group = "China"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "Final"
ruleset = "[]FINAL"

